#!/usr/bin/env python3
"""Build a 3-IDR hev1 fixture with old hvcC and a persistent in-band PPS update.

Inputs must be one-frame 4-byte-length HEVC MP4s generated by the host runner.
The muxed fixture keeps the first MP4's hvcC and emits: old frame, new parameter
sets + new frame, new frame without parameter sets. No encoder or BSF is used
while muxing, so the exact in-band update cannot be normalized away.
"""
import argparse
import json
import struct
from pathlib import Path


def boxes(data):
    pos = 0
    while pos < len(data):
        size, kind = struct.unpack_from('>I4s', data, pos)
        if size < 8 or pos + size > len(data):
            raise ValueError('Expected bounded 32-bit MP4 box')
        yield kind, data[pos + 8:pos + size]
        pos += size


def box(kind, data):
    return struct.pack('>I4s', len(data) + 8, kind) + data


def find_payload(data, kind):
    for typ, payload in boxes(data):
        if typ == kind:
            return payload
        if typ in (b'moov', b'trak', b'mdia', b'minf', b'stbl'):
            result = find_payload(payload, kind)
            if result is not None:
                return result
    return None


def parameters(data):
    stsd = find_payload(data, b'stsd')
    assert struct.unpack_from('>I', stsd, 4)[0] == 1
    sample = list(boxes(stsd[8:]))
    assert len(sample) == 1 and sample[0][0] in (b'hev1', b'hvc1')
    hvcc = dict(boxes(sample[0][1][78:]))[b'hvcC']
    assert len(hvcc) >= 23 and (hvcc[21] & 3) == 3
    pos, nalus = 23, bytearray()
    for _ in range(hvcc[22]):
        typ = hvcc[pos] & 63
        count = struct.unpack_from('>H', hvcc, pos + 1)[0]
        pos += 3
        for _ in range(count):
            size = struct.unpack_from('>H', hvcc, pos)[0]
            pos += 2
            assert pos + size <= len(hvcc)
            if typ in (32, 33, 34):
                nalus += struct.pack('>I', size) + hvcc[pos:pos + size]
            pos += size
    return bytes(nalus)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('old', type=Path)
    parser.add_argument('new', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    old, new = args.old.read_bytes(), args.new.read_bytes()
    samples = [find_payload(old, b'mdat'), parameters(new) + find_payload(new, b'mdat'),
               find_payload(new, b'mdat')]
    # Validate the simple input shape rather than silently rewriting a general MP4.
    for data in (old, new):
        stsz = find_payload(data, b'stsz')
        assert struct.unpack_from('>I', stsz, 8)[0] == 1
        assert len(find_payload(data, b'mdat')) == struct.unpack_from('>I', stsz, 4)[0]
    prefix = b''.join(box(k, d) for k, d in boxes(old) if k not in (b'moov', b'mdat'))
    chunk_offset = len(prefix) + 8

    def rewrite(data):
        output = bytearray()
        for typ, payload in boxes(data):
            p = bytearray(payload)
            if typ in (b'moov', b'trak', b'mdia', b'minf', b'stbl', b'edts'):
                p = rewrite(payload)
            elif typ == b'stsz':
                p = struct.pack('>III', 0, 0, len(samples)) + b''.join(struct.pack('>I', len(s)) for s in samples)
            elif typ == b'stsc':
                p = struct.pack('>IIIII', 0, 1, 1, len(samples), 1)
            elif typ == b'stco':
                p = struct.pack('>III', 0, 1, chunk_offset)
            elif typ == b'stts':
                assert struct.unpack_from('>II', p, 4) == (1, 1)
                struct.pack_into('>I', p, 8, len(samples))
            elif typ in (b'mvhd', b'mdhd', b'tkhd'):
                assert p[0] == 0
                offset = 20 if typ == b'tkhd' else 16
                struct.pack_into('>I', p, offset, struct.unpack_from('>I', p, offset)[0] * len(samples))
            elif typ == b'elst':
                assert p[0] == 0 and struct.unpack_from('>I', p, 4)[0] == 1
                struct.pack_into('>I', p, 8, struct.unpack_from('>I', p, 8)[0] * len(samples))
            elif typ in (b'ctts', b'co64', b'stss'):
                raise ValueError(f'Unexpected input table {typ!r}')
            output += box(typ, p)
        return output

    moov = find_payload(old, b'moov')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(prefix + box(b'mdat', b''.join(samples)) + box(b'moov', rewrite(moov)))
    print(json.dumps({'output': str(args.output), 'frames': 3,
                      'sample_sizes': [len(s) for s in samples],
                      'expected_pixels': ['old input frame', 'new input frame', 'new input frame'],
                      'hvcC': 'unchanged old input hvcC'}, indent=2))


if __name__ == '__main__':
    main()
